package chocolate.gui;

import java.io.IOException;
import java.util.Collections;

import javafx.collections.FXCollections;
import javafx.collections.ObservableList;
import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.geometry.Pos;
import javafx.scene.Node;
import javafx.scene.control.Label;
import javafx.scene.layout.HBox;

/**
 * A chat dialogue containing the speaker name and message text.
 */
public class DialogBox extends HBox {
    @FXML
    private Label speaker;
    @FXML
    private Label dialog;

    private DialogBox(String speakerName, String text) {
        try {
            FXMLLoader loader = new FXMLLoader(MainWindow.class.getResource("/view/DialogBox.fxml"));
            loader.setController(this);
            loader.setRoot(this);
            loader.load();
        } catch (IOException e) {
            throw new IllegalStateException("Unable to load a chat dialog.", e);
        }

        speaker.setText(speakerName);
        dialog.setText(text);
    }

    /**
     * Reverses the dialogue layout so that it represents Chocolate.
     */
    private void flip() {
        ObservableList<Node> children = FXCollections.observableArrayList(getChildren());
        Collections.reverse(children);
        getChildren().setAll(children);
        setAlignment(Pos.TOP_LEFT);
        getStyleClass().add("chocolate-dialog");
    }

    /**
     * Creates a right-aligned dialogue for the user.
     *
     * @param text Text entered by the user.
     * @return User dialogue box.
     */
    public static DialogBox getUserDialog(String text) {
        DialogBox dialogBox = new DialogBox("You", text);
        dialogBox.getStyleClass().add("user-dialog");
        return dialogBox;
    }

    /**
     * Creates a left-aligned dialogue for Chocolate.
     *
     * @param text Reply generated by Chocolate.
     * @return Chocolate dialogue box.
     */
    public static DialogBox getChocolateDialog(String text) {
        DialogBox dialogBox = new DialogBox("Chocolate", text);
        dialogBox.flip();
        return dialogBox;
    }
}
